import { Niri, String } from "../waybruh/globals.slint";

component Workspace inherits Rectangle {
    in property <bool> is-active;
    in property <string> index;

    in-out property <color> active-color: whitesmoke;
    in-out property <color> non-active-color: #6e6a86;

    Text {
        text: String.indian-to-roman(index);
        color: is-active ? active-color : non-active-color;
    }

    opacity: 0;  
    animate opacity { duration: 300ms; easing: ease-in; }  
  
    init => {  
        // Start invisible; animate will transition to opacity: 1  
        self.opacity = 1;  
    }
}

export component NiriWorkspaces inherits HorizontalLayout {
    spacing: 5px;

    for workspace in Niri.workspaces: Workspace {
        is-active: workspace.is-active;
        index: workspace.index;
    }
}
