import { Niri, String } from "../waybruh/globals.slint";

component Workspace inherits Rectangle {
    in property <bool> is-active;
    in property <string> index;

    in-out property <color> active-color: whitesmoke;
    in-out property <color> non-active-color: #6e6a86;

    Text {
        text: String.indian-to-roman(index);
        color: is-active ? active-color : non-active-color;
        font-size: is-active ? 9pt : 8pt;

        animate color { duration: 200ms; }
        
        animate font-size {
            duration: 400ms;
            easing: ease-in-out-back;
        }
    }

    opacity: 0;

    animate opacity {
        duration: 400ms;
        easing: ease-in;
    }

    animate x {
        duration: 600ms;
        easing: ease-out-bounce;
    }

    y: -20px;

    animate y {
        duration: 200ms;
        easing: ease-out-quad;
    }

    init => {
        self.opacity = 1;
        self.y = 0;
    }
}

export component NiriWorkspaces inherits Rectangle {
    property <length> item-width: 8pt;
    property <length> item-spacing: 10pt;

    width: Niri.workspaces.length * (item-width + item-spacing) - item-spacing;

    for niri-workspace[i] in Niri.workspaces: Workspace {
        width: item-width;
        x: i * (self.width + item-spacing);

        is-active: niri-workspace.is-active;
        index: niri-workspace.index;
    }
}
