import { Date } from "../waybruh/globals.slint";

export enum TimeStyle {
    Time,
    Date,
}

export component Time {
    property <string> format: " %H:%M:%S";
    property <TimeStyle> style: TimeStyle.Time;

    timer := Timer {
        interval: 1s;
        running: true;

        triggered => {
            text.text = Date.current-time(format);
        }
    }

    TouchArea {
        text := Text {
            text: Date.current-time(format);
            color: white;
        }

        clicked => {
            if (style == TimeStyle.Time) {
                style = TimeStyle.Date;
                format = " %H:%M   %Y, %d %B, %A";
                timer.interval = 60s;
            } else {
                style = TimeStyle.Time;
                format = " %H:%M:%S";
                timer.interval = 1s;
            }

            text.text = Date.current-time(format);
        }
    }
}
