import { Button } from "std-widgets.slint";
import { Shell } from "waybruh/globals.slint";

export component BruhBar inherits Window {
    width: 100px;
    height: 100px;

    property <string> text: "hello, world";

    HorizontalLayout {
        Text {
            text: root.text;
            color: black;
            font-size: 24pt;
        }

        Button {
            clicked => {
                root.text = Shell.execute("head -c 8 /dev/random");
            }
        }
    }
}
