import { Button } from "std-widgets.slint";
import { Bar, BarLayout } from "waybruh/bar.slint";
import { ModulesLeft, ModulesCenter, ModulesRight } from "modules.slint";

export component BruhBar inherits Bar {
    exclusive-zone: 15px;
    default-font-size: 8pt;
    default-font-family: "JetBrainsMono Nerd Font";

    BarLayout {
        ModulesLeft {
            x: 0;
            y: 0;
            height <=> root.exclusive-zone;
        }

        ModulesCenter {
            x: (parent.width - self.width) / 2;
            y: 0;
            height <=> root.exclusive-zone;
        }

        ModulesRight {
            x: parent.width - self.width;
            y: 0;
            height <=> root.exclusive-zone;
        }
    }
}
