import { Button } from "std-widgets.slint";
import { Bar } from "waybruh/bar.slint";

export component BruhBar inherits Bar {
    default-font-size: 12pt;

    VerticalLayout {
        HorizontalLayout {
            // Match drawn content's height to the exclusive zone
            height <=> root.exclusive-zone;

            Button {
                width: 50%;

                clicked => {
                    self.text = root.width / 1px;
                    root.exclusive-zone += 20px;
                }
            }

            Button {
                width: 50%;

                clicked => {
                    self.text = root.height / 1px;
                    root.exclusive-zone -= 20px;
                }
            }
        }
    }
}
