import { Date, Hyprland, Niri, ActiveCompositor } from "waybruh/globals.slint";
import { Time } from "modules/time.slint";
import { KeyboardLayout } from "modules/keyboard_layout.slint";
import { OpaqueSeparator, DottedSeparator } from "modules/separators.slint";
import { NiriWorkspaces } from "modules/niri-workspaces.slint";
import { WindowTitle } from "modules/window-title.slint";
import { Power } from "modules/power.slint";

component Modules inherits HorizontalLayout {
    @children
}

export component ModulesLeft inherits Modules {
    alignment: start;
    padding-left: 6px;
    spacing: 3px;
    width: 42%;

    OpaqueSeparator { }
    WindowTitle { }
}

export component ModulesCenter inherits Modules {
    alignment: center;
    spacing: 3px;
    width: 25%;

    DottedSeparator { }
    Time { }
    OpaqueSeparator { }
    NiriWorkspaces { }
    DottedSeparator { }
}

export component ModulesRight inherits Modules {
    alignment: end;
    spacing: 3px;
    padding-right: 6px;
    width: 33%;

    KeyboardLayout { }
    Power { }
}
