import { Date, Hyprland } from "waybruh/globals.slint";
import { Time } from "modules/time.slint";
import { OpaqueSeparator, DottedSeparator } from "modules/separators.slint";

component Modules inherits HorizontalLayout {
    @children
}

export component ModulesLeft inherits Modules {
    alignment: start;
    padding-left: 6px;

    Text {
        text <=> Hyprland.active-window-title;
        color: white;
    }
}

export component ModulesCenter inherits Modules {
    alignment: center;

    DottedSeparator { }
    Time { }
    OpaqueSeparator { }
}

export component ModulesRight inherits Modules {
    alignment: end;
    padding-right: 6px;

    Text {
        text: "Modules Right";
        color: white;
    }
}
