import { Date } from "waybruh/globals.slint";

component Modules inherits HorizontalLayout {
    @children
}

component Time {
    in-out property <string> format: " {>02:h}:{>02:m}:{>02:s}";

    Timer {
        interval: 1s;
        running: true;

        triggered => {
            text.text = Date.current-time(format);
        }
    }

    text := Text {
        text: Date.current-time(format);
        color: white;
    }
}

export component ModulesLeft inherits Modules {
    alignment: start;
    padding-left: 6px;

    Text {
        text: "Modules Left";
        color: white;
    }
}

export component ModulesCenter inherits Modules {
    alignment: center;

    Text {
        text: "Modules Center | ";
        color: white;
    }
    
    Time { }
}

export component ModulesRight inherits Modules {
    alignment: end;
    padding-right: 6px;

    Text {
        text: "Modules Right";
        color: white;
    }
}
