import { System } from "globals.slint";

export component Bar inherits Window {
    title: "Waybruh";
    background: transparent;
    in-out property <length> exclusive-zone: 15px;

    changed exclusive-zone => {
        if (self.exclusive-zone < 0) {
            self.exclusive-zone = 0px;
        } else {
            // changed callback will run twice here
            System.exclusive-zone-changed(self.exclusive-zone);
        }
    };
}

export component BarLayout inherits Rectangle {
    in property <length> exclusive-zone;

    width: 100%;
    height <=> root.exclusive-zone;
    x: 0px;
    y: 0px;

    @children
}
