import { System } from "globals.slint";

export component Bar inherits Window {
    title: "Waybruh";
    background: transparent;
    in-out property <length> exclusive-zone: 15px;

    changed exclusive-zone => {
        if (self.exclusive-zone < 0) {
            self.exclusive-zone = 0px;
        } else {
            // changed callback will run twice here
            System.exclusive-zone-changed(self.exclusive-zone);
        }
    };
}

export component BarLayout inherits VerticalLayout {
    in property <length> exclusive-zone;

    alignment: start;
    width: 100%;
    height: 100%;

    HorizontalLayout {
        // Match drawn content's height to the exclusive zone
        height <=> root.exclusive-zone;

        @children
    }
}
