export struct ProgramOutput {
    stdout: string,
    stderr: string,
    exit_code: int,
}

export global Shell {
    callback execute(string) -> ProgramOutput;
}

export global Command {
    callback execute([string]) -> ProgramOutput;
}

export global String {
    pure callback trim(string) -> string;
    pure callback trim-start(string) -> string;
    pure callback trim-end(string) -> string;
}
