export struct ProgramOutput {
    stdout: string,
    stderr: string,
    exit_code: int,
}

export global Shell {
    callback execute(string) -> ProgramOutput;
}

export global Command {
    callback execute([string]) -> ProgramOutput;
}

export global System {
    callback exclusive-zone-changed(length);
}

export global Date {
    pure callback current-time(string) -> string;
}

export global Hyprland {
    out property <string> active-window-title;
    out property <string> active-window-class;
    out property <string> active-window-address;

    out property <string> active-workspace-id;
    out property <string> active-workspace-name;

    out property <string> focused-monitor-name;
    out property <string> focused-monitor-workspace-id;
    out property <string> focused-monitor-workspace-name;

    out property <bool> entered-fullscreen;

    out property <string> active-keyboard-layout;
}

struct NiriWorkspace {
    index: string,
    name: string,
    output: string,
    is-active: bool,
    is-focused: bool,
    is-urgent: bool,
}

export global Niri {
    out property <string> active-window-title;
    out property <string> active-window-class;
    out property <string> active-workspace;
    out property <string> active-keyboard-layout;
    out property <string> active-window-pid;

    out property <bool> overview-opened;

    out property <[NiriWorkspace]> workspaces;
}

export global ActiveCompositor {
    out property <string> active-window-title;
    out property <string> active-window-class;
    out property <string> active-workspace;
    out property <string> active-keyboard-layout;
}
